# Generated by Django 4.1.3 on 2024-10-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0013_alter_memorialdecalculo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiarioMemorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14)),
                ("cota", models.DecimalField(decimal_places=2, max_digits=5)),
                ("agencia_cc", models.CharField(max_length=20)),
                ("ir", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "contribuicao_previdencia",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cpm", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "auxilio_liquido",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "memorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiarios",
                        to="militares.memorialdecalculo",
                    ),
                ),
            ],
        ),
    ]
