# Generated by Django 4.1.3 on 2024-10-31 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0014_beneficiariomemorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorialdecalculo",
            name="data_criacao",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
